// source: pricedrops.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.pricedrop_query_proto.ApplyPriceDropReq', null, global);
goog.exportSymbol('proto.pricedrop_query_proto.ApplyPriceDropResp', null, global);
goog.exportSymbol('proto.pricedrop_query_proto.ChildProduct', null, global);
goog.exportSymbol('proto.pricedrop_query_proto.ProdWithChildren', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pricedrop_query_proto.ChildProduct = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pricedrop_query_proto.ChildProduct, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pricedrop_query_proto.ChildProduct.displayName = 'proto.pricedrop_query_proto.ChildProduct';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pricedrop_query_proto.ProdWithChildren = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pricedrop_query_proto.ProdWithChildren.repeatedFields_, null);
};
goog.inherits(proto.pricedrop_query_proto.ProdWithChildren, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pricedrop_query_proto.ProdWithChildren.displayName = 'proto.pricedrop_query_proto.ProdWithChildren';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pricedrop_query_proto.ApplyPriceDropReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pricedrop_query_proto.ApplyPriceDropReq.repeatedFields_, null);
};
goog.inherits(proto.pricedrop_query_proto.ApplyPriceDropReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pricedrop_query_proto.ApplyPriceDropReq.displayName = 'proto.pricedrop_query_proto.ApplyPriceDropReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pricedrop_query_proto.ApplyPriceDropResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pricedrop_query_proto.ApplyPriceDropResp.repeatedFields_, null);
};
goog.inherits(proto.pricedrop_query_proto.ApplyPriceDropResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pricedrop_query_proto.ApplyPriceDropResp.displayName = 'proto.pricedrop_query_proto.ApplyPriceDropResp';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pricedrop_query_proto.ChildProduct.prototype.toObject = function(opt_includeInstance) {
  return proto.pricedrop_query_proto.ChildProduct.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pricedrop_query_proto.ChildProduct} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pricedrop_query_proto.ChildProduct.toObject = function(includeInstance, msg) {
  var f, obj = {
    discount: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    discountType: jspb.Message.getFieldWithDefault(msg, 2, ""),
    moq: jspb.Message.getFieldWithDefault(msg, 3, 0),
    mrp: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    pricePerUnit: jspb.Message.getFieldWithDefault(msg, 5, ""),
    priceTlCommission: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    priceTlSingleBuy: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    skuId: jspb.Message.getFieldWithDefault(msg, 8, ""),
    customText: jspb.Message.getFieldWithDefault(msg, 9, ""),
    customSymbol: jspb.Message.getFieldWithDefault(msg, 10, ""),
    couponCode: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pricedrop_query_proto.ChildProduct}
 */
proto.pricedrop_query_proto.ChildProduct.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pricedrop_query_proto.ChildProduct;
  return proto.pricedrop_query_proto.ChildProduct.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pricedrop_query_proto.ChildProduct} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pricedrop_query_proto.ChildProduct}
 */
proto.pricedrop_query_proto.ChildProduct.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setDiscount(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDiscountType(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMoq(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMrp(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPricePerUnit(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPriceTlCommission(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPriceTlSingleBuy(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setSkuId(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustomText(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustomSymbol(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setCouponCode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pricedrop_query_proto.ChildProduct.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pricedrop_query_proto.ChildProduct.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pricedrop_query_proto.ChildProduct} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pricedrop_query_proto.ChildProduct.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDiscount();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getDiscountType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMoq();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getMrp();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getPricePerUnit();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPriceTlCommission();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getPriceTlSingleBuy();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getSkuId();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getCustomText();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getCustomSymbol();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getCouponCode();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional float discount = 1;
 * @return {number}
 */
proto.pricedrop_query_proto.ChildProduct.prototype.getDiscount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pricedrop_query_proto.ChildProduct} returns this
 */
proto.pricedrop_query_proto.ChildProduct.prototype.setDiscount = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional string discount_type = 2;
 * @return {string}
 */
proto.pricedrop_query_proto.ChildProduct.prototype.getDiscountType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pricedrop_query_proto.ChildProduct} returns this
 */
proto.pricedrop_query_proto.ChildProduct.prototype.setDiscountType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 moq = 3;
 * @return {number}
 */
proto.pricedrop_query_proto.ChildProduct.prototype.getMoq = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.pricedrop_query_proto.ChildProduct} returns this
 */
proto.pricedrop_query_proto.ChildProduct.prototype.setMoq = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional float mrp = 4;
 * @return {number}
 */
proto.pricedrop_query_proto.ChildProduct.prototype.getMrp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pricedrop_query_proto.ChildProduct} returns this
 */
proto.pricedrop_query_proto.ChildProduct.prototype.setMrp = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional string price_per_unit = 5;
 * @return {string}
 */
proto.pricedrop_query_proto.ChildProduct.prototype.getPricePerUnit = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.pricedrop_query_proto.ChildProduct} returns this
 */
proto.pricedrop_query_proto.ChildProduct.prototype.setPricePerUnit = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional float price_tl_commission = 6;
 * @return {number}
 */
proto.pricedrop_query_proto.ChildProduct.prototype.getPriceTlCommission = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pricedrop_query_proto.ChildProduct} returns this
 */
proto.pricedrop_query_proto.ChildProduct.prototype.setPriceTlCommission = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional float price_tl_single_buy = 7;
 * @return {number}
 */
proto.pricedrop_query_proto.ChildProduct.prototype.getPriceTlSingleBuy = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pricedrop_query_proto.ChildProduct} returns this
 */
proto.pricedrop_query_proto.ChildProduct.prototype.setPriceTlSingleBuy = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional string sku_id = 8;
 * @return {string}
 */
proto.pricedrop_query_proto.ChildProduct.prototype.getSkuId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.pricedrop_query_proto.ChildProduct} returns this
 */
proto.pricedrop_query_proto.ChildProduct.prototype.setSkuId = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string custom_text = 9;
 * @return {string}
 */
proto.pricedrop_query_proto.ChildProduct.prototype.getCustomText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.pricedrop_query_proto.ChildProduct} returns this
 */
proto.pricedrop_query_proto.ChildProduct.prototype.setCustomText = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string custom_symbol = 10;
 * @return {string}
 */
proto.pricedrop_query_proto.ChildProduct.prototype.getCustomSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.pricedrop_query_proto.ChildProduct} returns this
 */
proto.pricedrop_query_proto.ChildProduct.prototype.setCustomSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string coupon_code = 11;
 * @return {string}
 */
proto.pricedrop_query_proto.ChildProduct.prototype.getCouponCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.pricedrop_query_proto.ChildProduct} returns this
 */
proto.pricedrop_query_proto.ChildProduct.prototype.setCouponCode = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pricedrop_query_proto.ProdWithChildren.repeatedFields_ = [13];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.toObject = function(opt_includeInstance) {
  return proto.pricedrop_query_proto.ProdWithChildren.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pricedrop_query_proto.ProdWithChildren} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pricedrop_query_proto.ProdWithChildren.toObject = function(includeInstance, msg) {
  var f, obj = {
    discount: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    discountType: jspb.Message.getFieldWithDefault(msg, 2, ""),
    moq: jspb.Message.getFieldWithDefault(msg, 3, 0),
    mrp: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    pricePerUnit: jspb.Message.getFieldWithDefault(msg, 5, ""),
    priceTlCommission: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    priceTlSingleBuy: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    skuId: jspb.Message.getFieldWithDefault(msg, 8, ""),
    customText: jspb.Message.getFieldWithDefault(msg, 9, ""),
    customSymbol: jspb.Message.getFieldWithDefault(msg, 10, ""),
    couponCode: jspb.Message.getFieldWithDefault(msg, 11, ""),
    minCartValue: jspb.Message.getFloatingPointFieldWithDefault(msg, 12, 0.0),
    childrenList: jspb.Message.toObjectList(msg.getChildrenList(),
    proto.pricedrop_query_proto.ChildProduct.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pricedrop_query_proto.ProdWithChildren}
 */
proto.pricedrop_query_proto.ProdWithChildren.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pricedrop_query_proto.ProdWithChildren;
  return proto.pricedrop_query_proto.ProdWithChildren.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pricedrop_query_proto.ProdWithChildren} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pricedrop_query_proto.ProdWithChildren}
 */
proto.pricedrop_query_proto.ProdWithChildren.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setDiscount(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDiscountType(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMoq(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMrp(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPricePerUnit(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPriceTlCommission(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPriceTlSingleBuy(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setSkuId(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustomText(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustomSymbol(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setCouponCode(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMinCartValue(value);
      break;
    case 13:
      var value = new proto.pricedrop_query_proto.ChildProduct;
      reader.readMessage(value,proto.pricedrop_query_proto.ChildProduct.deserializeBinaryFromReader);
      msg.addChildren(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pricedrop_query_proto.ProdWithChildren.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pricedrop_query_proto.ProdWithChildren} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pricedrop_query_proto.ProdWithChildren.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDiscount();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getDiscountType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMoq();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getMrp();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getPricePerUnit();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPriceTlCommission();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getPriceTlSingleBuy();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getSkuId();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getCustomText();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getCustomSymbol();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getCouponCode();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getMinCartValue();
  if (f !== 0.0) {
    writer.writeFloat(
      12,
      f
    );
  }
  f = message.getChildrenList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      proto.pricedrop_query_proto.ChildProduct.serializeBinaryToWriter
    );
  }
};


/**
 * optional float discount = 1;
 * @return {number}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.getDiscount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pricedrop_query_proto.ProdWithChildren} returns this
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.setDiscount = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional string discount_type = 2;
 * @return {string}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.getDiscountType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pricedrop_query_proto.ProdWithChildren} returns this
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.setDiscountType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 moq = 3;
 * @return {number}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.getMoq = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.pricedrop_query_proto.ProdWithChildren} returns this
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.setMoq = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional float mrp = 4;
 * @return {number}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.getMrp = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pricedrop_query_proto.ProdWithChildren} returns this
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.setMrp = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional string price_per_unit = 5;
 * @return {string}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.getPricePerUnit = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.pricedrop_query_proto.ProdWithChildren} returns this
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.setPricePerUnit = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional float price_tl_commission = 6;
 * @return {number}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.getPriceTlCommission = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pricedrop_query_proto.ProdWithChildren} returns this
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.setPriceTlCommission = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional float price_tl_single_buy = 7;
 * @return {number}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.getPriceTlSingleBuy = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pricedrop_query_proto.ProdWithChildren} returns this
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.setPriceTlSingleBuy = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional string sku_id = 8;
 * @return {string}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.getSkuId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.pricedrop_query_proto.ProdWithChildren} returns this
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.setSkuId = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string custom_text = 9;
 * @return {string}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.getCustomText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.pricedrop_query_proto.ProdWithChildren} returns this
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.setCustomText = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string custom_symbol = 10;
 * @return {string}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.getCustomSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.pricedrop_query_proto.ProdWithChildren} returns this
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.setCustomSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string coupon_code = 11;
 * @return {string}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.getCouponCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.pricedrop_query_proto.ProdWithChildren} returns this
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.setCouponCode = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional float min_cart_value = 12;
 * @return {number}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.getMinCartValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 12, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.pricedrop_query_proto.ProdWithChildren} returns this
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.setMinCartValue = function(value) {
  return jspb.Message.setProto3FloatField(this, 12, value);
};


/**
 * repeated ChildProduct children = 13;
 * @return {!Array<!proto.pricedrop_query_proto.ChildProduct>}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.getChildrenList = function() {
  return /** @type{!Array<!proto.pricedrop_query_proto.ChildProduct>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pricedrop_query_proto.ChildProduct, 13));
};


/**
 * @param {!Array<!proto.pricedrop_query_proto.ChildProduct>} value
 * @return {!proto.pricedrop_query_proto.ProdWithChildren} returns this
*/
proto.pricedrop_query_proto.ProdWithChildren.prototype.setChildrenList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.pricedrop_query_proto.ChildProduct=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pricedrop_query_proto.ChildProduct}
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.addChildren = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.pricedrop_query_proto.ChildProduct, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pricedrop_query_proto.ProdWithChildren} returns this
 */
proto.pricedrop_query_proto.ProdWithChildren.prototype.clearChildrenList = function() {
  return this.setChildrenList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.repeatedFields_ = [1,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.toObject = function(opt_includeInstance) {
  return proto.pricedrop_query_proto.ApplyPriceDropReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pricedrop_query_proto.ApplyPriceDropReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    productsinputList: jspb.Message.toObjectList(msg.getProductsinputList(),
    proto.pricedrop_query_proto.ProdWithChildren.toObject, includeInstance),
    catalogueName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    usertagsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    traceId: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pricedrop_query_proto.ApplyPriceDropReq}
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pricedrop_query_proto.ApplyPriceDropReq;
  return proto.pricedrop_query_proto.ApplyPriceDropReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pricedrop_query_proto.ApplyPriceDropReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pricedrop_query_proto.ApplyPriceDropReq}
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.pricedrop_query_proto.ProdWithChildren;
      reader.readMessage(value,proto.pricedrop_query_proto.ProdWithChildren.deserializeBinaryFromReader);
      msg.addProductsinput(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCatalogueName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addUsertags(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTraceId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pricedrop_query_proto.ApplyPriceDropReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pricedrop_query_proto.ApplyPriceDropReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProductsinputList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.pricedrop_query_proto.ProdWithChildren.serializeBinaryToWriter
    );
  }
  f = message.getCatalogueName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUsertagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * repeated ProdWithChildren productsInput = 1;
 * @return {!Array<!proto.pricedrop_query_proto.ProdWithChildren>}
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.getProductsinputList = function() {
  return /** @type{!Array<!proto.pricedrop_query_proto.ProdWithChildren>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pricedrop_query_proto.ProdWithChildren, 1));
};


/**
 * @param {!Array<!proto.pricedrop_query_proto.ProdWithChildren>} value
 * @return {!proto.pricedrop_query_proto.ApplyPriceDropReq} returns this
*/
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.setProductsinputList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.pricedrop_query_proto.ProdWithChildren=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pricedrop_query_proto.ProdWithChildren}
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.addProductsinput = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.pricedrop_query_proto.ProdWithChildren, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pricedrop_query_proto.ApplyPriceDropReq} returns this
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.clearProductsinputList = function() {
  return this.setProductsinputList([]);
};


/**
 * optional string catalogue_name = 2;
 * @return {string}
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.getCatalogueName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pricedrop_query_proto.ApplyPriceDropReq} returns this
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.setCatalogueName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string userTags = 3;
 * @return {!Array<string>}
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.getUsertagsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pricedrop_query_proto.ApplyPriceDropReq} returns this
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.setUsertagsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pricedrop_query_proto.ApplyPriceDropReq} returns this
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.addUsertags = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pricedrop_query_proto.ApplyPriceDropReq} returns this
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.clearUsertagsList = function() {
  return this.setUsertagsList([]);
};


/**
 * optional string trace_id = 4;
 * @return {string}
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.getTraceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.pricedrop_query_proto.ApplyPriceDropReq} returns this
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.setTraceId = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pricedrop_query_proto.ApplyPriceDropReq} returns this
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.clearTraceId = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pricedrop_query_proto.ApplyPriceDropReq.prototype.hasTraceId = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pricedrop_query_proto.ApplyPriceDropResp.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pricedrop_query_proto.ApplyPriceDropResp.prototype.toObject = function(opt_includeInstance) {
  return proto.pricedrop_query_proto.ApplyPriceDropResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pricedrop_query_proto.ApplyPriceDropResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pricedrop_query_proto.ApplyPriceDropResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    productsoutputList: jspb.Message.toObjectList(msg.getProductsoutputList(),
    proto.pricedrop_query_proto.ProdWithChildren.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pricedrop_query_proto.ApplyPriceDropResp}
 */
proto.pricedrop_query_proto.ApplyPriceDropResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pricedrop_query_proto.ApplyPriceDropResp;
  return proto.pricedrop_query_proto.ApplyPriceDropResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pricedrop_query_proto.ApplyPriceDropResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pricedrop_query_proto.ApplyPriceDropResp}
 */
proto.pricedrop_query_proto.ApplyPriceDropResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.pricedrop_query_proto.ProdWithChildren;
      reader.readMessage(value,proto.pricedrop_query_proto.ProdWithChildren.deserializeBinaryFromReader);
      msg.addProductsoutput(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pricedrop_query_proto.ApplyPriceDropResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pricedrop_query_proto.ApplyPriceDropResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pricedrop_query_proto.ApplyPriceDropResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pricedrop_query_proto.ApplyPriceDropResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProductsoutputList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.pricedrop_query_proto.ProdWithChildren.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ProdWithChildren productsOutput = 1;
 * @return {!Array<!proto.pricedrop_query_proto.ProdWithChildren>}
 */
proto.pricedrop_query_proto.ApplyPriceDropResp.prototype.getProductsoutputList = function() {
  return /** @type{!Array<!proto.pricedrop_query_proto.ProdWithChildren>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pricedrop_query_proto.ProdWithChildren, 1));
};


/**
 * @param {!Array<!proto.pricedrop_query_proto.ProdWithChildren>} value
 * @return {!proto.pricedrop_query_proto.ApplyPriceDropResp} returns this
*/
proto.pricedrop_query_proto.ApplyPriceDropResp.prototype.setProductsoutputList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.pricedrop_query_proto.ProdWithChildren=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pricedrop_query_proto.ProdWithChildren}
 */
proto.pricedrop_query_proto.ApplyPriceDropResp.prototype.addProductsoutput = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.pricedrop_query_proto.ProdWithChildren, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pricedrop_query_proto.ApplyPriceDropResp} returns this
 */
proto.pricedrop_query_proto.ApplyPriceDropResp.prototype.clearProductsoutputList = function() {
  return this.setProductsoutputList([]);
};


goog.object.extend(exports, proto.pricedrop_query_proto);
